/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package botmanagergui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Chris
 */
public class BotManagerGUI extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public BotManagerGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotConfigChooser = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LoadBotConfig = new javax.swing.JMenuItem();
        BotsMenu = new javax.swing.JMenu();
        StartBotMgr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IRC Bot Manager");

        BotConfigChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Chris\\Code"));

        FileMenu.setText("File");

        LoadBotConfig.setText("Load Bot Config...");
        LoadBotConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBotConfigActionPerformed(evt);
            }
        });
        FileMenu.add(LoadBotConfig);

        jMenuBar1.add(FileMenu);

        BotsMenu.setText("Bots");

        StartBotMgr.setText("Start Bot Manager...");
        StartBotMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBotMgrActionPerformed(evt);
            }
        });
        BotsMenu.add(StartBotMgr);

        jMenuBar1.add(BotsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotConfigChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addComponent(BotConfigChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadBotConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBotConfigActionPerformed
        try {
            int returnVal = BotConfigChooser.showOpenDialog(BotManagerGUI.this);
			
			if (returnVal == JFileChooser.APPROVE_OPTION) {
				File file = BotConfigChooser.getSelectedFile();
				if (file.canRead()) {
					
				}
			}
        } catch (java.awt.HeadlessException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_LoadBotConfigActionPerformed

    private void StartBotMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBotMgrActionPerformed
        BotLog.append("Bot Manager started...\n");
    }//GEN-LAST:event_StartBotMgrActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BotManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BotManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BotManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BotManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				BotManagerGUI gui = new BotManagerGUI();
				gui.setLocationRelativeTo(null);
				gui.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser BotConfigChooser;
    private javax.swing.JMenu BotsMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem LoadBotConfig;
    private javax.swing.JMenuItem StartBotMgr;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
